trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  variables:
  - group: NOTIFY_VAR
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: git fetch --unshallow
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonar-cloud'
        organization: 'jonatancon1'
        scannerMode: 'Other'
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        codeCoverageClassFilesDirectories: 'build/classes/main/'
        codeCoverageFailIfEmpty: true
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: true
        sqGradlePluginVersionChoice: 'build'
        spotBugsAnalysis: false
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
        reportDirectory: '$(Build.SourcesDirectory)/build/reports/jacoco/test/html'
    
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
    - task: Docker@2
      inputs:
        repository: 'java-app'
        command: 'build'
        Dockerfile: '**/dockerfile'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'container-resgister'
        regionName: 'us-east-1'
        imageSource: 'imageid'
        sourceImageId: 'java-app:$(Build.BuildId)'
        repositoryName: 'application-app'
        pushTag: '$(Build.BuildId)'
        forceDockerNamingConventions: true
        logRequest: true
        logResponse: true
    - template: azure-pipelines/notify.yml