version: '3.9'

services:
  java_app:
    container_name: java_app
    image: "jrstark01/practice:latest"
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://dev-devops.cncurixahrmu.us-east-1.rds.amazonaws.com:3306/users
      - DATASOURCE_USERNAME=admin
      - DATASOURCE_PASSWORD=admin123456789
      - DATASOURCE_DRIVER=com.mysql.cj.jdbc.Driver
      - DATASOURCE_TYPE=com.zaxxer.hikari.HikariDataSource
      - TOMCAT_MAX_ACTIVE=1
      - TOMCAT_MIN_IDLE=1
      - JPA_HIBERNATE_DDL_AUTO=update
      - JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - JPA_SHOW_SQL=true
      - PROFILE=dev
      - PORT=8080