spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER}
    type: ${DATASOURCE_TYPE}
    hikari:
      maximumPoolSize: ${TOMCAT_MAX_ACTIVE}
      minimumIdle: ${TOMCAT_MIN_IDLE}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${JPA_PROPERTIES_HIBERNATE_DIALECT}
        format_sql: ${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    show-sql: ${JPA_SHOW_SQL}