spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://dev-devops.cncurixahrmu.us-east-1.rds.amazonaws.com:3306/users}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin123456789}
    driverClassName: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    type: ${DATASOURCE_TYPE:com.zaxxer.hikari.HikariDataSource}
    hikari:
      maximumPoolSize: ${TOMCAT_MAX_ACTIVE:1}
      minimumIdle: ${TOMCAT_MIN_IDLE:1}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
        format_sql: ${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
    show-sql: ${JPA_SHOW_SQL:true}
#spring:
#  datasource:
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#    driverClassName: ${DATASOURCE_DRIVER}
#    type: ${DATASOURCE_TYPE}
#    hikari:
#      maximumPoolSize: ${TOMCAT_MAX_ACTIVE}
#      minimumIdle: ${TOMCAT_MIN_IDLE}
#  jpa:
#    hibernate:
#      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
#    properties:
#      hibernate:
#        dialect: ${JPA_PROPERTIES_HIBERNATE_DIALECT}
#        format_sql: ${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
#    show-sql: ${JPA_SHOW_SQL}

