server:
  port: 8080
spring:
  messages:
    basename: messages
    encoding: utf-8
  profiles:
    active: dev
  mvc:
    log-request-details: true
  web:
    locale: en_US
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
          servlet:
            org.springframework.web.servlet.DispatcherServlet: DEBUG